[build]
builder = "nixpacks"
buildCommand = "npm install --no-package-lock"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.pre-deploy]]
command = "echo 'Checking environment variables...'"
